#pragma once
#define MODELTOWORLD "modelToWorld"
#define WORLDTOVIEW "worldToView"
#define VIEWTOPROJECTION "viewToProjection"
#define CAMERAPOSITION "cameraPosition"
#define SPECULARITY "specularity"
#define SHADOWTEXTURE "shadowTexture"
#define LIGHTVIEW "lightView"
#define LIGHTPROJECTION "lightProjection"
#define LIGHTPOSITION "lightPosition"
#define LIGHTCOLOR "lightColor"
#define AMBIENTLIGHT "ambientLight"
#define ANIMATIONMATRICES "animationMatrices"